const ADMIN="lorielsilvadosreis014@gmail.com";let minutes=10,intensity="leve",circuit=[],idx=0,phase="exercise",left=40,interval=null,sound=true;
const pool={leve:[["Marcha no lugar","🌿"],["Mobilidade de ombros","🔄"],["Agachamento lento","🦵"],["Elevação de joelhos leve","🚶"],["Prancha adaptada","🧘"],["Alongamento dinâmico","🤸"]],forte:[["Polichinelos","🔥"],["Agachamentos","🦵"],["Flexões adaptadas","💪"],["Mountain climbers","⚡"],["Corrida parada","🏃"],["Prancha","🧱"],["Pular corda imaginária","🪢"]]};
const $=id=>document.getElementById(id);function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function make(){let n=minutes===10?5:minutes===15?7:9,p=shuffle(pool[intensity]);circuit=Array.from({length:n},(_,i)=>p[i%p.length]);render();reset()}
function render(){$("summary").textContent=circuit.length+" exercícios";$("round").textContent=`Rodada 0 / ${circuit.length}`;$("list").innerHTML=circuit.map((x,i)=>`<div class="exercise"><div><b>${i+1}. ${x[1]} ${x[0]}</b><small>40s exercício • 20s descanso</small></div><strong>20s</strong></div>`).join("")}
function fmt(n){return "00:"+String(Math.max(0,n)).padStart(2,"0")}function ui(){ $("time").textContent=fmt(left);$("phase").textContent=phase==="exercise"?"EXERCÍCIO":"DESCANSO";$("round").textContent=`Rodada ${Math.min(idx+1,circuit.length)} / ${circuit.length}`;$("exercise").textContent=phase==="exercise"?(circuit[idx]?.[0]||"Pronto"):"Respire e descanse";let total=phase==="exercise"?40:20;$("bar").style.width=((total-left)/total*100)+"%"}
function beep(f=700){if(!sound)return;try{let C=AudioContext||webkitAudioContext,c=new C,o=c.createOscillator(),g=c.createGain();o.frequency.value=f;o.connect(g);g.connect(c.destination);g.gain.value=.05;o.start();o.stop(c.currentTime+.12)}catch(e){}}
function reset(){clearInterval(interval);interval=null;idx=0;phase="exercise";left=40;ui()}
function start(){if(!circuit.length)make();if(interval)return;interval=setInterval(()=>{left--;if(left<=0){beep(phase==="exercise"?500:900);if(phase==="exercise"){phase="rest";left=20}else{idx++;if(idx>=circuit.length){clearInterval(interval);interval=null;$("phase").textContent="CONCLUÍDO";$("exercise").textContent="🔥 Treino finalizado!";$("bar").style.width="100%";beep(1000);return}phase="exercise";left=40}}ui()},1000)}
document.querySelectorAll("#times button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#times button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");minutes=+b.dataset.min;make()});
document.querySelectorAll("#intensity button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#intensity button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");intensity=b.dataset.i;make()});
$("generate").onclick=make;$("start").onclick=start;$("pause").onclick=()=>{clearInterval(interval);interval=null};$("reset").onclick=reset;$("sound").onclick=()=>{sound=!sound;$("sound").textContent=sound?"🔊 Som ligado":"🔇 Som desligado"};
const modal=$("modal");$("login").onclick=()=>modal.classList.remove("hidden");$("login2").onclick=()=>modal.classList.remove("hidden");$("close").onclick=()=>modal.classList.add("hidden");
$("demo").onclick=()=>{modal.classList.add("hidden");let e=prompt("DEMO — informe o e-mail Google:");if(e){localStorage.setItem("morningfit_user",e);if(e.toLowerCase()===ADMIN.toLowerCase())$("admin").classList.remove("hidden");alert("Login demonstrativo concluído.")}};
$("export").onclick=()=>{let a=document.createElement("a");a.href="data:application/json,"+encodeURIComponent(JSON.stringify({minutes,intensity,circuit,admin:ADMIN},null,2));a.download="morningfit-config.json";a.click()};
$("clear").onclick=()=>{localStorage.clear();location.reload()};if(localStorage.getItem("morningfit_user")?.toLowerCase()===ADMIN.toLowerCase())$("admin").classList.remove("hidden");make();